#!/bin/sh
#

chmod +x {{pkg.svc_data_path}}

if [ ! -h {{pkg.svc_data_path}}/htdocs ]; then
  ln -s {{pkg.path}}/drupal {{pkg.svc_data_path}}/htdocs
fi

mkdir -p {{pkg.svc_data_path}}/cgi-bin
mkdir -p {{pkg.svc_var_path}}/logs
