#!/bin/sh
#

chmod +x {{pkg.svc_data_path}}

# Symlink drupal root
if [ -h {{pkg.svc_data_path}}/htdocs ]; then
  rm {{pkg.svc_data_path}}/htdocs
fi
ln -s {{pkg.path}}/{{pkg.name}} {{pkg.svc_data_path}}/htdocs

# Create files directory
mkdir -p {{pkg.svc_data_path}}/files
chown hab:hab {{pkg.svc_data_path}}/files

# Create settings.php
if [ ! -f {{pkg.svc_data_path}}/settings.php ]; then
  cp -H {{pkg.svc_data_path}}/htdocs/sites/default/default.settings.php {{pkg.svc_data_path}}/settings.php
  chown hab:hab {{pkg.svc_data_path}}/settings.php
fi

# Create php.ini
if [ ! -f {{pkg.svc_data_path}}/php.ini ]; then
  cp -L {{pkg.path}}/php.ini-production {{pkg.svc_data_path}}/php.ini
  # Enable opcache
  sed -i '/\[opcache\]/azend_extension=opcache.so' {{pkg.svc_data_path}}/php.ini
  sed -i '/^;opcache.enable=1/s/^;//' {{pkg.svc_data_path}}/php.ini
fi

mkdir -p {{pkg.svc_data_path}}/cgi-bin
mkdir -p {{pkg.svc_var_path}}/logs

# Install Drupal
if [ ! -f {{pkg.svc_data_path}}/htdocs/sites/default/files/.ht.sqlite ]; then
  drush site-install standard install_configure_form.update_status_module='array(FALSE,FALSE)' -y -r {{pkg.svc_data_path}}/htdocs --account-name=admin --account-pass=password --site-name="Habitat Drupal Demo" --db-url=sqlite://sites/default/files/.ht.sqlite
  # Set owner as 'hab' again
  chown -R hab:hab {{pkg.svc_data_path}}/files
  echo "Created Standard Drupal install with user 'admin' and password 'password'."
  echo "Visit http://localhost:8080 in web browser to view the Drupal demo site."
fi
